specific error if twitter account not found
Clipto-Platform/clipto-backend pull request #23
Opened 2022-05-04 13:20 UTC by seervidinesh

2022-05-04 14:11 UTC, AP-Atul requested changes

2022-05-04 14:11 UTC, AP-Atul commented on src/services/twitter.service.ts
> +    try {
Can you add another try-catch in `verifyTwitter` function? Thank you

2022-05-04 15:05 UTC, seervidinesh commented
@AP-Atul resolved your above comment.

2022-05-05 03:45 UTC, AP-Atul approved these changes

2022-05-05 03:46 UTC, merged